language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-20

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

script: ./gradlew check